### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by seesharper** [markjaquith/sveltekit-playwright-fetch-mock#7]
Hi @markjaquith 

You don't happen to have an example how to use this in PlayWright? 😀

I'm pretty new to SvelteKit and Playwright so anything pointing me in the right direction would be great 👍😀

**Comment by markjaquith** [comment]
@seesharper

So in your Playwright test, you'd import like:

```ts
import { mockFetch } from 'sveltekit-playwright-fetch-mock'
```

And then:

```ts
test('Example.com test', async ({ page }) => {
	await mockFetch(page, /^https:\/\/www\.example\.com\//, {
		somedata: 'example',
	})
	await page.goto('/some-local-route-that-fetches-example-dot-com')
	// Your assertions here.
})
```

So what this means is that when you go to `/some-local-route-that-fetches-example-dot-com` in your SvelteKit app, and the `+page.server.js` or `+page.server.ts` file for that route calls `fetch` (using the one that SvelteKit provides you) to get data from `https://www.example.com/`, this package will intercept that request and return `{ somedata: "example" }`

**Comment by seesharper** [comment]
Thanks a lot for responding so fast 😍.

This is what I've got so far 

```typescript
test('Example.com test', async ({ page }) => {
	await mockFetch(page, /^https:\/\/www\.nrk\.no\//, {
		somedata: 'example',
	});
	await page.goto('/login')
	// Your assertions here.
})

```
+page.server.ts

```typescript
import type { ServerLoadEvent } from '@sveltejs/kit';
import type { PageServerLoad } from './$types';

export const load = (async (event: ServerLoadEvent) => {

    let response = await event.fetch("https://www.nrk.no/")
    console.log(response);

    return { res: response.text() };
}) satisfies PageServerLoad;
```
+page.svelte

```typescript
<script lang="ts">
	import type { PageServerData } from './$types';

	export let data: PageServerData;
</script>

<h1>{data.res}</h1>

```

I still can't get it to return the mocked result. Do you see any obvious mistake here? 😃

**Comment by markjaquith** [comment]
The only mistakes are mine. One was fixed in version 0.5.3 — I created this package for use in a specific project, and I had accidentally left in a tiny bit of config that was unique to that project.

Next, there are more setup steps than I've outlined.

Here are the full instructions. I know it's a lot... not sure if there's a way to make it simpler.

`src/hooks.server.ts`

```ts
import type { HandleFetch, Handle } from '@sveltejs/kit'
import { sequence } from '@sveltejs/kit/hooks'
import {
	handle as handleHttpMocks,
	handleFetch as handleMockedResponses,
} from 'sveltekit-playwright-fetch-mock'
import { PUBLIC_LOCAL } from '$env/static/public'

export const handle = sequence(
	handleHttpMocks(PUBLIC_LOCAL === '1'),
) satisfies Handle

export const handleFetch = (async ({ request, fetch, event }) => {
	const mockedResponse = handleMockedResponses(request, event)

	if (mockedResponse) {
		return mockedResponse
	}

	return fetch(request)
}) satisfies HandleFetch

```

In your local and CI environments, add `PUBLIC_LOCAL=1` to your environment.

This is what tells the mock code to be active. You can name this however you like, if you also change the reference in `src/hooks.server.ts` to match it.

`src/app.d.ts`

```ts
type FetchMocks = Record<
	string,
	{
		status: number
		statusText: string
		headers?: Record<string, string>
		body: string
	}
>

declare namespace App {
	// interface Error {}
	interface Locals {
		fetchMocks: FetchMocks
		isPlaywright: boolean
	}
	// interface PageData {}
	// interface Platform {}
}
```

And finally in your Playwright test:

```ts
import { expect, test } from '@playwright/test'
import { mockFetch } from 'sveltekit-playwright-fetch-mock'

test('Example.com test', async ({ page }) => {
	await mockFetch(page, /^https:\/\/www\.example\.com\//, {
		somedata: 'example',
	})
	await page.goto('/some-local-route-that-fetches-example-dot-com')
	// Your Playwright assertions here.
})
```

So what this means is that when you go to `/some-local-route-that-fetches-example-dot-com` in your SvelteKit app, and the `+page.server.js` or `+page.server.ts` file for that route calls `fetch` (using the one that SvelteKit provides you) to get data from `https://www.example.com/`, this package will intercept that request and return `{ somedata: "example" }`

**Comment by markjaquith** [comment]
Here is a full working example: https://github.com/markjaquith/sveltekit-playwright-fetch-mock-example

**Comment by seesharper** [comment]
Ah, I just started looking into SvelteKit hooks before I left the office today. Had a feeling we were missing something to glue the whole thing together 😃. Again thanks a lot for taking the time to explain this in such detail. Appreciate it 👍😍

**Comment by seesharper** [comment]
It worked perfectly 👍. Thanks 😃
